spring:
  redis:
    host: 192.168.70.133
    password: 
    port: 6379
    pool:
      max-idle: 100
      min-idle: 1
      max-active: 1000
      max-wait: -1
  activemq:
    broker-url: tcp://192.168.70.133:61616
    user: admin
    password: admin
    in-memory: true
    pool:
      enabled: false